IBD/raw_sources/html/homepage.html

First version IBD frontpage

---

IBD/raw_sources/html/ibd_contact.html

fix contacts for ibd

---

README.md

Fix index of README for VKGL

---

BBMRI_eric/freemarker/view-entityreport-specific-eu_bbmri_eric_collections.ftl
BBMRI_eric/freemarker/view-standalone-report-specific-eu_bbmri_eric_collections.ftl

Freemarker templates for BBMRI-ERIC

---

BBMRI_eric/freemarker/view-entityreport-specific-eu_bbmri_eric_collections.ftl
BBMRI_eric/freemarker/view-standalone-report-specific-eu_bbmri_eric_collections.ftl

- Change +/- in collection view into bullets so users don’t mistake them for collapses
- Change ‘Back to biobanks’ in ‘Back to search results’

[FIX] FTL styling of subcollections/parent collections + rename button

---

VKGL/scripts/config_example.txt
VKGL/scripts/consensus/VKGL_consensus_table_generator.py
VKGL/scripts/consensus/molgenis.py

[FIX] Fixes according to last VKGL export

---

IBD/raw_sources/R/getPublicData_vMolgenisScript_without_comments.R
IBD/raw_sources/html/ibd_frontpage.html

* Add biopsies data to script and home
* Fix bug: samplecount and patientscount were mixed up between data types

[IBD] Add biopsies data to script and home and fix mix up bug 

---

LifeCycle/raw_sources/lifecycle_cohorts.html

[LIFECYCLE] Add new lines before info and access heading

---

freemarker-templates/datamodel-documentation.ftl

This report you can add to the 'attributes' entity in the data explorer to get nice overview of all packages, entities and their attributes including yUML diagrams of your data model. Alpha.
You can see it in action on https://molgenis09.gcc.rug.nl/menu/main/dataexplorer?entity=sys_md_Attribute&mod=entitiesreport

Created datamodel-documentation.ftl

---

BBMRI_eric/python/importDutchData.py
BBMRI_eric/python/importGermanData.py

[BBMRI-ERIC] Scripts to import data from Dutch and German servers

---

IBD/raw_sources/R/getPublicData_vMolgenisScript_without_comments.R
IBD/raw_sources/html/ibd_frontpage.html

[IBD] Add metabolomics and biopsies

---

README.md
chromosome6_project/chr6_bs3.css
chromosome6_project/chr6_bs4.css
chromosome6_project/homepage.html

[CHR6] Add chromosome6 project css and homepage

---

VKGL/scripts/counter/.gitignore
VKGL/scripts/counter/ConsensusCounter.py
VKGL/scripts/counter/Molgenis_config_parser.py
VKGL/scripts/counter/molgenis.py

[VKGL] VKGL consensus counter

---

IBD/raw_sources/R/getPublicData_vMolgenisScript_without_comments.R
IBD/raw_sources/html/ibd_frontpage.html

Add scrna to IBD homepage

---

LifeCycle/css/lifecycle_bootstrap4.css
LifeCycle/css/lifecycle_bootstrap4_variables.scss

fix(lifecycle): darker gray for secondary color

---

TMF:German_Biobank_Registry/css/bbmri-de4.css

fix: added mobile styling to bbmri de

---

BBMRI_nl/css/bbmri_nl_bootstrap4_theme.css

Edited:
line #32
Added:
#635 - #641
Rest is only linter.

fix: added correct styling to bbmri_nl css and fixed a typo

---

validate_attribute_metadata/readme.md
validate_attribute_metadata/validate_attribute_metadata.py

add project

---

.gitignore
remodel_lifecycle/README.md
remodel_lifecycle/requirements.txt

- uses python 3 venv
- add pandas dependancy to the requirements.txt
- Tested CSS (if applicable)

chore: Add setup for installing and running the mapper script

---

.gitignore

chore: Add (mac os ) file DS_Store to git ignore

---

remodel_lifecycle/remodel_lc_vars.py
remodel_lifecycle/target/RepeatedVariables.csv

add repeatedVariables

---

remodel_lifecycle/remodel_lc_vars.py

Script is rather slow now, we should do something about that.

fix RepeatedVariables

---

remodel_lifecycle/README.md
remodel_lifecycle/remodel_source_vars.py

remodel variable values for ALSPAC cohort
